from __future__ import annotations

from textwrap import dedent

from .models import InitChoices


def build_files(choices: InitChoices, cli_version: str) -> dict[str, str | dict]:
    files: dict[str, str | dict] = {}
    files[".gitignore"] = _gitignore()
    files["README.md"] = _root_readme(choices)
    files["rag.toml"] = _rag_toml(choices)
    files["create-rag-app.manifest.json"] = _manifest(choices, cli_version)
    if choices.include_sample_assets:
        files[".env.example"] = _env_example(choices.frontend)
        files["docs/sample.txt"] = SAMPLE_DOC
    files.update(_backend_files(choices))
    if choices.frontend == "nextjs":
        files.update(_nextjs_files())
    elif choices.frontend == "streamlit":
        files.update(_streamlit_files())
    return files


def _gitignore() -> str:
    return dedent(
        """
        .DS_Store
        .env
        .venv/
        __pycache__/
        *.pyc
        .pytest_cache/
        data/
        frontend/node_modules/
        frontend/.next/
        """
    ).lstrip()


def _root_readme(choices: InitChoices) -> str:
    frontend_commands = {
        "nextjs": dedent(
            """
            ## Frontend

            ```bash
            cd frontend
            npm install
            npm run dev
            ```
            """
        ).strip(),
        "streamlit": dedent(
            """
            ## Frontend

            ```bash
            cd frontend
            pip install -r requirements.txt
            streamlit run app.py
            ```
            """
        ).strip(),
        "backend-only": dedent(
            """
            ## Frontend

            No frontend scaffold was generated for this project.
            """
        ).strip(),
    }[choices.frontend]

    return (
        f"# {choices.project_name}\n\n"
        f"Generated by `create-rag-app` with the `{choices.frontend}` frontend option.\n\n"
        "## Project Layout\n\n"
        "- `backend/`: shared FastAPI backend with all RAG logic\n"
        "- `frontend/`: thin UI shell for `nextjs` or `streamlit`\n"
        "- `docs/`: local source files for ingestion\n"
        "- `rag.toml`: runtime config\n"
        "- `create-rag-app.manifest.json`: generator manifest\n\n"
        "## Setup\n\n"
        "```bash\n"
        "cp .env.example .env\n"
        "```\n\n"
        "## Backend\n\n"
        "```bash\n"
        "cd backend\n"
        "pip install -e .\n"
        "uvicorn app.main:app --reload\n"
        "```\n\n"
        "Ingest sample docs:\n\n"
        "```bash\n"
        "cd backend\n"
        "python -m app.scripts.ingest\n"
        "```\n\n"
        f"{frontend_commands}\n\n"
        "## API\n\n"
        "- `GET /health`\n"
        "- `POST /ingest`\n"
        "- `POST /chat`\n"
    )


def _rag_toml(choices: InitChoices) -> str:
    cors = {
        "nextjs": '["http://localhost:3000"]',
        "streamlit": '["http://localhost:8501"]',
        "backend-only": "[]",
    }[choices.frontend]
    return dedent(
        f"""
        [project]
        name = "{choices.project_name}"
        frontend = "{choices.frontend}"

        [docs]
        source_type = "{choices.document_source_type}"
        path = "./docs"

        [chunking]
        strategy = "{choices.chunking_strategy}"
        chunk_size = 800
        chunk_overlap = 120

        [embeddings]
        provider = "{choices.embedding_provider}"
        model = "text-embedding-3-small"

        [vector_store]
        provider = "{choices.vector_store}"
        path = "./data/chroma"
        collection = "documents"

        [retrieval]
        mode = "{choices.retrieval_mode}"
        top_k = 4

        [generation]
        provider = "openai"
        model = "gpt-4.1-mini"

        [server]
        host = "127.0.0.1"
        port = 8000
        cors_origins = {cors}
        """
    ).lstrip()


def _manifest(choices: InitChoices, cli_version: str) -> dict:
    return {
        "schema_version": "1",
        "generator": {"name": "create-rag-app", "version": cli_version},
        "project": {"name": choices.project_name, "frontend": choices.frontend},
        "backend": {
            "framework": "fastapi",
            "rag_profile": {
                "document_source_type": choices.document_source_type,
                "chunking_strategy": choices.chunking_strategy,
                "embedding_provider": choices.embedding_provider,
                "vector_store": choices.vector_store,
                "retrieval_mode": choices.retrieval_mode,
            },
        },
        "paths": {
            "backend_dir": "backend",
            "frontend_dir": None if choices.frontend == "backend-only" else "frontend",
            "config_file": "rag.toml",
        },
        "capabilities": {"ingest_api": True, "chat_api": True, "frontend_shell": choices.frontend != "backend-only"},
    }


def _env_example(frontend: str) -> str:
    return "OPENAI_API_KEY=\n"


def _backend_files(choices: InitChoices) -> dict[str, str]:
    files: dict[str, str] = {}
    files["backend/pyproject.toml"] = _backend_pyproject()
    files["backend/app/__init__.py"] = ""
    files["backend/app/main.py"] = BACKEND_MAIN
    files["backend/app/api/__init__.py"] = ""
    files["backend/app/api/routes/__init__.py"] = ""
    files["backend/app/api/routes/health.py"] = HEALTH_ROUTE
    files["backend/app/api/routes/ingest.py"] = INGEST_ROUTE
    files["backend/app/api/routes/chat.py"] = CHAT_ROUTE
    files["backend/app/core/__init__.py"] = ""
    files["backend/app/core/config.py"] = BACKEND_CONFIG
    files["backend/app/schemas/__init__.py"] = ""
    files["backend/app/schemas/ingest.py"] = SCHEMA_INGEST
    files["backend/app/schemas/chat.py"] = SCHEMA_CHAT
    files["backend/app/services/__init__.py"] = ""
    files["backend/app/services/ingest_service.py"] = INGEST_SERVICE
    files["backend/app/services/answer_service.py"] = ANSWER_SERVICE
    files["backend/app/rag/__init__.py"] = ""
    files["backend/app/rag/interfaces.py"] = RAG_INTERFACES
    files["backend/app/rag/document_loader.py"] = DOCUMENT_LOADER
    files["backend/app/rag/chunking.py"] = CHUNKING
    files["backend/app/rag/embeddings.py"] = EMBEDDINGS
    files["backend/app/rag/vector_store.py"] = VECTOR_STORE
    files["backend/app/rag/retrieval.py"] = RETRIEVAL
    files["backend/app/rag/prompts.py"] = PROMPTS
    files["backend/app/scripts/__init__.py"] = ""
    files["backend/app/scripts/ingest.py"] = INGEST_SCRIPT
    return files


def _backend_pyproject() -> str:
    return dedent(
        """
        [build-system]
        requires = ["setuptools>=68", "wheel"]
        build-backend = "setuptools.build_meta"

        [project]
        name = "rag-backend"
        version = "0.1.0"
        requires-python = ">=3.11"
        dependencies = [
          "chromadb>=0.5.0",
          "fastapi>=0.110.0",
          "openai>=1.30.0",
          "pydantic>=2.0.0",
          "python-dotenv>=1.0.1",
          "uvicorn>=0.29.0",
        ]

        [tool.setuptools]
        package-dir = {"" = "."}

        [tool.setuptools.packages.find]
        where = ["."]
        include = ["app*"]
        """
    ).lstrip()


def _nextjs_files() -> dict[str, str]:
    return {
        "frontend/package.json": NEXT_PACKAGE_JSON,
        "frontend/next.config.ts": NEXT_CONFIG,
        "frontend/tsconfig.json": NEXT_TSCONFIG,
        "frontend/next-env.d.ts": NEXT_ENV_D_TS,
        "frontend/app/layout.tsx": NEXT_LAYOUT,
        "frontend/app/page.tsx": NEXT_PAGE,
        "frontend/app/globals.css": NEXT_GLOBALS,
        "frontend/lib/api.ts": NEXT_API,
        "frontend/components/chat-shell.tsx": NEXT_CHAT_SHELL,
        "frontend/components/message-list.tsx": NEXT_MESSAGE_LIST,
        "frontend/components/composer.tsx": NEXT_COMPOSER,
        "frontend/components/ui/button.tsx": NEXT_BUTTON,
        "frontend/components/ui/input.tsx": NEXT_INPUT,
        "frontend/lib/types.ts": NEXT_TYPES,
    }


def _streamlit_files() -> dict[str, str]:
    return {
        "frontend/app.py": STREAMLIT_APP,
        "frontend/requirements.txt": STREAMLIT_REQUIREMENTS,
    }


SAMPLE_DOC = """create-rag-app generates opinionated retrieval apps.

The milestone one backend uses FastAPI, OpenAI embeddings, a Chroma vector store, and dense retrieval.
The frontend can be Next.js, Streamlit, or backend-only.
"""


BACKEND_MAIN = dedent(
    """
    from fastapi import FastAPI
    from fastapi.middleware.cors import CORSMiddleware

    from app.api.routes.chat import router as chat_router
    from app.api.routes.health import router as health_router
    from app.api.routes.ingest import router as ingest_router
    from app.core.config import get_settings


    def create_app() -> FastAPI:
        settings = get_settings()
        app = FastAPI(title=f"{settings.project_name} API")

        if settings.cors_origins:
            app.add_middleware(
                CORSMiddleware,
                allow_origins=settings.cors_origins,
                allow_credentials=True,
                allow_methods=["*"],
                allow_headers=["*"],
            )

        app.include_router(health_router)
        app.include_router(ingest_router)
        app.include_router(chat_router)
        return app


    app = create_app()
    """
).lstrip()


HEALTH_ROUTE = dedent(
    """
    from fastapi import APIRouter

    from app.core.config import get_settings

    router = APIRouter(tags=["health"])


    @router.get("/health")
    def health() -> dict:
        settings = get_settings()
        return {
            "status": "ok",
            "project": settings.project_name,
            "frontend": settings.frontend,
            "document_source_type": settings.document_source_type,
            "chunking_strategy": settings.chunking_strategy,
            "embedding_provider": settings.embedding_provider,
            "vector_store": settings.vector_store,
            "retrieval_mode": settings.retrieval_mode,
        }
    """
).lstrip()


INGEST_ROUTE = dedent(
    """
    from fastapi import APIRouter

    from app.schemas.ingest import IngestResponse
    from app.services.ingest_service import ingest_documents

    router = APIRouter(tags=["ingest"])


    @router.post("/ingest", response_model=IngestResponse)
    def ingest() -> IngestResponse:
        return ingest_documents()
    """
).lstrip()


CHAT_ROUTE = dedent(
    """
    from fastapi import APIRouter

    from app.schemas.chat import ChatRequest, ChatResponse
    from app.services.answer_service import answer_question

    router = APIRouter(tags=["chat"])


    @router.post("/chat", response_model=ChatResponse)
    def chat(request: ChatRequest) -> ChatResponse:
        return answer_question(request.message)
    """
).lstrip()


BACKEND_CONFIG = dedent(
    """
    from __future__ import annotations

    import os
    import tomllib
    from dataclasses import dataclass
    from functools import lru_cache
    from pathlib import Path

    from dotenv import load_dotenv


    @dataclass(frozen=True)
    class Settings:
        project_name: str
        frontend: str
        document_source_type: str
        docs_path: Path
        chunking_strategy: str
        chunk_size: int
        chunk_overlap: int
        embedding_provider: str
        embedding_model: str
        vector_store: str
        vector_store_path: Path
        vector_collection: str
        retrieval_mode: str
        top_k: int
        generation_model: str
        cors_origins: list[str]
        openai_api_key: str


    PROJECT_ROOT = Path(__file__).resolve().parents[3]
    CONFIG_PATH = PROJECT_ROOT / "rag.toml"
    ENV_PATH = PROJECT_ROOT / ".env"


    def _load_toml() -> dict:
        with CONFIG_PATH.open("rb") as handle:
            return tomllib.load(handle)


    @lru_cache(maxsize=1)
    def get_settings() -> Settings:
        load_dotenv(ENV_PATH)
        raw = _load_toml()
        openai_api_key = os.environ.get("OPENAI_API_KEY", "")

        return Settings(
            project_name=raw["project"]["name"],
            frontend=raw["project"]["frontend"],
            document_source_type=raw["docs"]["source_type"],
            docs_path=(PROJECT_ROOT / raw["docs"]["path"]).resolve(),
            chunking_strategy=raw["chunking"]["strategy"],
            chunk_size=raw["chunking"]["chunk_size"],
            chunk_overlap=raw["chunking"]["chunk_overlap"],
            embedding_provider=raw["embeddings"]["provider"],
            embedding_model=raw["embeddings"]["model"],
            vector_store=raw["vector_store"]["provider"],
            vector_store_path=(PROJECT_ROOT / raw["vector_store"]["path"]).resolve(),
            vector_collection=raw["vector_store"]["collection"],
            retrieval_mode=raw["retrieval"]["mode"],
            top_k=raw["retrieval"]["top_k"],
            generation_model=raw["generation"]["model"],
            cors_origins=list(raw["server"]["cors_origins"]),
            openai_api_key=openai_api_key,
        )
    """
).lstrip()


SCHEMA_INGEST = dedent(
    """
    from pydantic import BaseModel


    class IngestResponse(BaseModel):
        files_indexed: int
        chunks_indexed: int
        collection: str
    """
).lstrip()


SCHEMA_CHAT = dedent(
    """
    from pydantic import BaseModel


    class ChatRequest(BaseModel):
        message: str


    class ChatSource(BaseModel):
        path: str
        chunk_id: str
        text: str


    class ChatResponse(BaseModel):
        answer: str
        sources: list[ChatSource]
    """
).lstrip()


INGEST_SERVICE = dedent(
    """
    from app.core.config import get_settings
    from app.rag.chunking import RecursiveChunker
    from app.rag.document_loader import load_local_documents
    from app.rag.embeddings import OpenAIEmbeddingClient
    from app.rag.vector_store import ChromaVectorStore
    from app.schemas.ingest import IngestResponse


    def ingest_documents() -> IngestResponse:
        settings = get_settings()
        documents = load_local_documents(settings.docs_path)
        chunker = RecursiveChunker(settings.chunk_size, settings.chunk_overlap)
        chunks = chunker.split_documents(documents)
        embedder = OpenAIEmbeddingClient(
            api_key=settings.openai_api_key,
            model=settings.embedding_model,
        )
        store = ChromaVectorStore(settings.vector_store_path, settings.vector_collection)
        store.upsert(chunks, embedder.embed_many([chunk["text"] for chunk in chunks]))
        return IngestResponse(
            files_indexed=len(documents),
            chunks_indexed=len(chunks),
            collection=settings.vector_collection,
        )
    """
).lstrip()


ANSWER_SERVICE = dedent(
    """
    from openai import OpenAI

    from app.core.config import get_settings
    from app.rag.embeddings import OpenAIEmbeddingClient
    from app.rag.prompts import build_answer_prompt
    from app.rag.retrieval import DenseRetriever
    from app.rag.vector_store import ChromaVectorStore
    from app.schemas.chat import ChatResponse, ChatSource


    def answer_question(message: str) -> ChatResponse:
        settings = get_settings()
        embedder = OpenAIEmbeddingClient(
            api_key=settings.openai_api_key,
            model=settings.embedding_model,
        )
        store = ChromaVectorStore(settings.vector_store_path, settings.vector_collection)
        retriever = DenseRetriever(store=store, embedder=embedder, top_k=settings.top_k)
        results = retriever.retrieve(message)

        client = OpenAI(api_key=settings.openai_api_key)
        prompt = build_answer_prompt(message, results)
        completion = client.responses.create(model=settings.generation_model, input=prompt)
        answer = completion.output_text

        return ChatResponse(
            answer=answer,
            sources=[
                ChatSource(path=item["path"], chunk_id=item["chunk_id"], text=item["text"])
                for item in results
            ],
        )
    """
).lstrip()


RAG_INTERFACES = dedent(
    """
    from __future__ import annotations

    from typing import Protocol


    class Chunker(Protocol):
        def split_documents(self, documents: list[dict[str, str]]) -> list[dict[str, str]]: ...


    class Embedder(Protocol):
        def embed_many(self, texts: list[str]) -> list[list[float]]: ...
        def embed_one(self, text: str) -> list[float]: ...


    class VectorStore(Protocol):
        def upsert(self, chunks: list[dict[str, str]], embeddings: list[list[float]]) -> None: ...
        def query(self, embedding: list[float], top_k: int) -> list[dict[str, str]]: ...
    """
).lstrip()


DOCUMENT_LOADER = dedent(
    """
    from pathlib import Path


    SUPPORTED_EXTENSIONS = {".txt", ".md"}


    def load_local_documents(docs_path: Path) -> list[dict[str, str]]:
        documents: list[dict[str, str]] = []
        for path in sorted(docs_path.rglob("*")):
            if not path.is_file() or path.suffix.lower() not in SUPPORTED_EXTENSIONS:
                continue
            documents.append(
                {
                    "path": str(path.relative_to(docs_path.parent)),
                    "text": path.read_text(encoding="utf-8"),
                }
            )
        return documents
    """
).lstrip()


CHUNKING = dedent(
    """
    class RecursiveChunker:
        def __init__(self, chunk_size: int, chunk_overlap: int) -> None:
            self.chunk_size = chunk_size
            self.chunk_overlap = chunk_overlap
            self.separators = ["\\n\\n", "\\n", ". ", " "]


        def split_documents(self, documents: list[dict[str, str]]) -> list[dict[str, str]]:
            chunks: list[dict[str, str]] = []
            for document in documents:
                parts = self._split_text(document["text"])
                for index, text in enumerate(parts):
                    chunks.append(
                        {
                            "chunk_id": f"{document['path']}:{index}",
                            "path": document["path"],
                            "text": text,
                        }
                    )
            return chunks


        def _split_text(self, text: str) -> list[str]:
            text = text.strip()
            if len(text) <= self.chunk_size:
                return [text] if text else []

            for separator in self.separators:
                segments = self._chunk_by_separator(text, separator)
                if segments:
                    return segments

            return self._hard_split(text)


        def _chunk_by_separator(self, text: str, separator: str) -> list[str]:
            pieces = text.split(separator)
            if len(pieces) == 1:
                return []

            chunks: list[str] = []
            current = ""
            for piece in pieces:
                candidate = piece if not current else f"{current}{separator}{piece}"
                if len(candidate) <= self.chunk_size:
                    current = candidate
                    continue
                if current:
                    chunks.append(current.strip())
                current = piece

            if current:
                chunks.append(current.strip())

            normalized = [item for chunk in chunks for item in self._hard_split(chunk)]
            return normalized


        def _hard_split(self, text: str) -> list[str]:
            chunks: list[str] = []
            start = 0
            while start < len(text):
                end = min(len(text), start + self.chunk_size)
                chunks.append(text[start:end].strip())
                if end == len(text):
                    break
                start = max(0, end - self.chunk_overlap)
            return [chunk for chunk in chunks if chunk]
    """
).lstrip()


EMBEDDINGS = dedent(
    """
    from openai import OpenAI


    class OpenAIEmbeddingClient:
        def __init__(self, api_key: str, model: str) -> None:
            self.client = OpenAI(api_key=api_key)
            self.model = model


        def embed_many(self, texts: list[str]) -> list[list[float]]:
            response = self.client.embeddings.create(model=self.model, input=texts)
            return [item.embedding for item in response.data]


        def embed_one(self, text: str) -> list[float]:
            return self.embed_many([text])[0]
    """
).lstrip()


VECTOR_STORE = dedent(
    """
    from pathlib import Path

    import chromadb


    class ChromaVectorStore:
        def __init__(self, persist_path: Path, collection_name: str) -> None:
            persist_path.mkdir(parents=True, exist_ok=True)
            self.client = chromadb.PersistentClient(path=str(persist_path))
            self.collection = self.client.get_or_create_collection(name=collection_name)


        def upsert(self, chunks: list[dict[str, str]], embeddings: list[list[float]]) -> None:
            self.collection.upsert(
                ids=[chunk["chunk_id"] for chunk in chunks],
                embeddings=embeddings,
                documents=[chunk["text"] for chunk in chunks],
                metadatas=[
                    {"path": chunk["path"], "chunk_id": chunk["chunk_id"]}
                    for chunk in chunks
                ],
            )


        def query(self, embedding: list[float], top_k: int) -> list[dict[str, str]]:
            response = self.collection.query(
                query_embeddings=[embedding],
                n_results=top_k,
            )
            matches: list[dict[str, str]] = []
            documents = response.get("documents", [[]])[0]
            metadatas = response.get("metadatas", [[]])[0]
            for metadata, text in zip(metadatas, documents, strict=False):
                matches.append(
                    {
                        "path": metadata["path"],
                        "chunk_id": metadata["chunk_id"],
                        "text": text,
                    }
                )
            return matches
    """
).lstrip()


RETRIEVAL = dedent(
    """
    class DenseRetriever:
        def __init__(self, store, embedder, top_k: int) -> None:
            self.store = store
            self.embedder = embedder
            self.top_k = top_k


        def retrieve(self, query: str) -> list[dict[str, str]]:
            embedding = self.embedder.embed_one(query)
            return self.store.query(embedding, self.top_k)
    """
).lstrip()


PROMPTS = dedent(
    """
    def build_answer_prompt(question: str, context_chunks: list[dict[str, str]]) -> str:
        context = "\\n\\n".join(
            f"[{item['path']}::{item['chunk_id']}]\\n{item['text']}" for item in context_chunks
        )
        return (
            "You are a concise RAG assistant. Answer using only the provided context. "
            "If the answer is not in the context, say you do not know.\\n\\n"
            f"Context:\\n{context}\\n\\n"
            f"Question: {question}"
        )
    """
).lstrip()


INGEST_SCRIPT = dedent(
    """
    from app.services.ingest_service import ingest_documents


    if __name__ == "__main__":
        result = ingest_documents()
        print(
            f"Indexed {result.files_indexed} files into {result.collection} "
            f"({result.chunks_indexed} chunks)"
        )
    """
).lstrip()


NEXT_PACKAGE_JSON = dedent(
    """
    {
      "name": "frontend",
      "private": true,
      "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start"
      },
      "dependencies": {
        "next": "15.0.0",
        "react": "18.3.1",
        "react-dom": "18.3.1"
      },
      "devDependencies": {
        "@types/node": "22.10.1",
        "@types/react": "18.3.12",
        "@types/react-dom": "18.3.1",
        "typescript": "5.6.3"
      }
    }
    """
).lstrip()


NEXT_CONFIG = dedent(
    """
    import type { NextConfig } from "next";

    const nextConfig: NextConfig = {
      reactStrictMode: true,
    };

    export default nextConfig;
    """
).lstrip()


NEXT_TSCONFIG = dedent(
    """
    {
      "compilerOptions": {
        "target": "ES2020",
        "lib": ["dom", "dom.iterable", "es2020"],
        "allowJs": false,
        "skipLibCheck": true,
        "strict": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "bundler",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true
      },
      "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
      "exclude": ["node_modules"]
    }
    """
).lstrip()


NEXT_ENV_D_TS = dedent(
    """
    /// <reference types="next" />
    /// <reference types="next/image-types/global" />

    // This file is generated by Next.js and should not be edited manually.
    """
).lstrip()


NEXT_LAYOUT = dedent(
    """
    import "./globals.css";
    import type { Metadata } from "next";

    export const metadata: Metadata = {
      title: "RAG Chat",
      description: "Minimal HTTP frontend for the FastAPI RAG backend",
    };

    export default function RootLayout({ children }: { children: React.ReactNode }) {
      return (
        <html lang="en">
          <body>{children}</body>
        </html>
      );
    }
    """
).lstrip()


NEXT_PAGE = dedent(
    """
    import { ChatShell } from "../components/chat-shell";

    export default function HomePage() {
      return <ChatShell />;
    }
    """
).lstrip()


NEXT_GLOBALS = dedent(
    """
    :root {
      --bg: #f4efe7;
      --panel: rgba(255, 255, 255, 0.78);
      --ink: #1f2937;
      --muted: #5b6473;
      --border: rgba(31, 41, 55, 0.12);
      --accent: #0f766e;
      --accent-strong: #115e59;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      min-height: 100vh;
      font-family: Georgia, "Times New Roman", serif;
      color: var(--ink);
      background:
        radial-gradient(circle at top left, rgba(15, 118, 110, 0.18), transparent 28%),
        linear-gradient(180deg, #f7f1e8 0%, #efe7db 100%);
    }

    button,
    input,
    textarea {
      font: inherit;
    }

    .shell {
      max-width: 960px;
      margin: 0 auto;
      padding: 40px 20px 56px;
    }

    .hero {
      margin-bottom: 24px;
    }

    .hero h1 {
      margin: 0 0 8px;
      font-size: clamp(2.2rem, 4vw, 4rem);
      line-height: 0.96;
    }

    .hero p {
      margin: 0;
      max-width: 640px;
      color: var(--muted);
      font-size: 1.05rem;
    }

    .card {
      background: var(--panel);
      border: 1px solid var(--border);
      backdrop-filter: blur(14px);
      border-radius: 24px;
      box-shadow: 0 18px 40px rgba(31, 41, 55, 0.08);
    }

    .messages {
      display: grid;
      gap: 14px;
      padding: 20px;
      min-height: 420px;
    }

    .message {
      padding: 16px;
      border-radius: 18px;
      border: 1px solid var(--border);
      background: rgba(255, 255, 255, 0.66);
    }

    .message.user {
      background: rgba(15, 118, 110, 0.1);
    }

    .message-role {
      display: inline-block;
      margin-bottom: 8px;
      font-size: 0.8rem;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: var(--muted);
    }

    .sources {
      margin-top: 12px;
      display: grid;
      gap: 10px;
    }

    .source {
      padding: 12px;
      border-radius: 14px;
      background: rgba(15, 118, 110, 0.06);
    }

    .composer {
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 12px;
      padding: 16px 20px 20px;
    }

    .input {
      width: 100%;
      padding: 14px 16px;
      border-radius: 16px;
      border: 1px solid var(--border);
      background: rgba(255, 255, 255, 0.85);
      color: var(--ink);
    }

    .button {
      border: 0;
      border-radius: 16px;
      padding: 0 20px;
      min-height: 52px;
      background: var(--accent);
      color: white;
      cursor: pointer;
    }

    .button:hover {
      background: var(--accent-strong);
    }

    .status {
      margin: 14px 0 0;
      color: var(--muted);
      font-size: 0.95rem;
    }

    @media (max-width: 720px) {
      .composer {
        grid-template-columns: 1fr;
      }
    }
    """
).lstrip()


NEXT_API = dedent(
    """
    import { ChatResponse } from "./types";

    const API_BASE_URL =
      process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";

    export async function sendMessage(message: string): Promise<ChatResponse> {
      const response = await fetch(`${API_BASE_URL}/chat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message }),
      });

      if (!response.ok) {
        throw new Error("Backend request failed");
      }

      return response.json();
    }
    """
).lstrip()


NEXT_CHAT_SHELL = dedent(
    """
    "use client";

    import { FormEvent, useState } from "react";

    import { sendMessage } from "../lib/api";
    import { Composer } from "./composer";
    import { MessageList } from "./message-list";
    import { ChatMessage } from "../lib/types";

    const initialMessage: ChatMessage = {
      role: "assistant",
      content: "Ask about the sample docs after you ingest them.",
      sources: [],
    };

    export function ChatShell() {
      const [messages, setMessages] = useState<ChatMessage[]>([initialMessage]);
      const [value, setValue] = useState("");
      const [loading, setLoading] = useState(false);
      const [status, setStatus] = useState("Backend: http://localhost:8000");

      async function onSubmit(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();
        const message = value.trim();
        if (!message || loading) {
          return;
        }

        setLoading(true);
        setValue("");
        setMessages((current) => [...current, { role: "user", content: message, sources: [] }]);

        try {
          const response = await sendMessage(message);
          setMessages((current) => [
            ...current,
            {
              role: "assistant",
              content: response.answer,
              sources: response.sources,
            },
          ]);
          setStatus(`Retrieved ${response.sources.length} source chunks`);
        } catch (error) {
          const content =
            error instanceof Error ? error.message : "Unknown backend error";
          setMessages((current) => [
            ...current,
            { role: "assistant", content, sources: [] },
          ]);
          setStatus("Request failed");
        } finally {
          setLoading(false);
        }
      }

      return (
        <main className="shell">
          <section className="hero">
            <h1>Readable RAG.</h1>
            <p>
              This frontend is a thin shell. Retrieval, ingestion, and answer generation all stay in FastAPI.
            </p>
            <p className="status">{status}</p>
          </section>
          <section className="card">
            <MessageList messages={messages} loading={loading} />
            <Composer value={value} onChange={setValue} onSubmit={onSubmit} loading={loading} />
          </section>
        </main>
      );
    }
    """
).lstrip()


NEXT_MESSAGE_LIST = dedent(
    """
    import { ChatMessage } from "../lib/types";

    type MessageListProps = {
      messages: ChatMessage[];
      loading: boolean;
    };

    export function MessageList({ messages, loading }: MessageListProps) {
      return (
        <div className="messages">
          {messages.map((message, index) => (
            <article className={`message ${message.role}`} key={`${message.role}-${index}`}>
              <span className="message-role">{message.role}</span>
              <div>{message.content}</div>
              {message.sources.length > 0 ? (
                <div className="sources">
                  {message.sources.map((source) => (
                    <div className="source" key={source.chunk_id}>
                      <strong>{source.path}</strong>
                      <div>{source.text}</div>
                    </div>
                  ))}
                </div>
              ) : null}
            </article>
          ))}
          {loading ? <article className="message assistant">Thinking...</article> : null}
        </div>
      );
    }
    """
).lstrip()


NEXT_COMPOSER = dedent(
    """
    import { FormEvent } from "react";

    import { Button } from "./ui/button";
    import { Input } from "./ui/input";

    type ComposerProps = {
      value: string;
      onChange: (value: string) => void;
      onSubmit: (event: FormEvent<HTMLFormElement>) => void;
      loading: boolean;
    };

    export function Composer({ value, onChange, onSubmit, loading }: ComposerProps) {
      return (
        <form className="composer" onSubmit={onSubmit}>
          <Input
            value={value}
            onChange={(event) => onChange(event.target.value)}
            placeholder="Ask the backend about your docs"
          />
          <Button disabled={loading} type="submit">
            {loading ? "Sending..." : "Send"}
          </Button>
        </form>
      );
    }
    """
).lstrip()


NEXT_BUTTON = dedent(
    """
    import { ButtonHTMLAttributes } from "react";

    export function Button(props: ButtonHTMLAttributes<HTMLButtonElement>) {
      return <button className="button" {...props} />;
    }
    """
).lstrip()


NEXT_INPUT = dedent(
    """
    import { InputHTMLAttributes } from "react";

    export function Input(props: InputHTMLAttributes<HTMLInputElement>) {
      return <input className="input" {...props} />;
    }
    """
).lstrip()


NEXT_TYPES = dedent(
    """
    export type ChatSource = {
      path: string;
      chunk_id: string;
      text: string;
    };

    export type ChatMessage = {
      role: "user" | "assistant";
      content: string;
      sources: ChatSource[];
    };

    export type ChatResponse = {
      answer: string;
      sources: ChatSource[];
    };
    """
).lstrip()


STREAMLIT_REQUIREMENTS = dedent(
    """
    requests>=2.32.0
    streamlit>=1.40.0
    """
).lstrip()


STREAMLIT_APP = dedent(
    """
    import os

    import requests
    import streamlit as st


    BACKEND_URL = os.getenv("STREAMLIT_BACKEND_URL", "http://localhost:8000")

    st.set_page_config(page_title="RAG Chat", page_icon=":books:")
    st.title("RAG Chat")
    st.caption("Thin Streamlit shell on top of the FastAPI backend")

    if "messages" not in st.session_state:
        st.session_state.messages = []

    try:
        health = requests.get(f"{BACKEND_URL}/health", timeout=5)
        if health.ok:
            st.success(f"Backend ready: {BACKEND_URL}")
        else:
            st.warning("Backend health check failed")
    except requests.RequestException:
        st.warning(f"Backend unavailable at {BACKEND_URL}")

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.write(message["content"])
            for source in message.get("sources", []):
                with st.expander(source["path"]):
                    st.write(source["text"])

    prompt = st.chat_input("Ask the backend about your docs")
    if prompt:
        st.session_state.messages.append({"role": "user", "content": prompt, "sources": []})
        with st.chat_message("user"):
            st.write(prompt)

        try:
            response = requests.post(
                f"{BACKEND_URL}/chat",
                json={"message": prompt},
                timeout=60,
            )
            response.raise_for_status()
            payload = response.json()
            assistant_message = {
                "role": "assistant",
                "content": payload["answer"],
                "sources": payload["sources"],
            }
        except requests.RequestException as exc:
            assistant_message = {
                "role": "assistant",
                "content": f"Request failed: {exc}",
                "sources": [],
            }

        st.session_state.messages.append(assistant_message)
        with st.chat_message("assistant"):
            st.write(assistant_message["content"])
            for source in assistant_message["sources"]:
                with st.expander(source["path"]):
                    st.write(source["text"])
    """
).lstrip()
